bug fix

diff --git a/bin/java8 b/bin/java8
--- a/bin/java8
+++ b/bin/java8
@@ -1,2 +1,13 @@
-#!/bin/sh
-exec "$(java_home -v 1.8.0_202)/bin/java" "$@"
+#!/bin/bash
+JAVA_HOME=$(compgen -G "/Library/Java/JavaVirtualMachines/jdk1.8*.jdk/Contents/Home")
+if [[ -z $JAVA_HOME ]]; then
+	echo "Unable to find any JVMs matching version \"1.8\"." >&2
+	JAVA_HOME=$(/usr/libexec/java_home)
+fi
+
+export JAVA_HOME
+export PATH="$JAVA_HOME/bin:$PATH"
+
+if [[ ${0##*/} == java* ]]; then
+	exec java "$@"
+fi
